
mono:
  - latest
  - 4.2.2

language: csharp
solution: com.esendex.sdk.sln
install:
  - nuget restore com.esendex.sdk.sln
  - nuget install NUnit.Runners -Version 2.6.2 -OutputDirectory testrunner
script:
  - xbuild .solution/build.msbuild
  - mono ./testrunner/NUnit.Runners.2.6.2/tools/nunit-console.exe ./test/bin/Release/com.esendex.sdk.test.dll
  
cache:
  directories:
    - packages
